# Generated by Django 3.2.16 on 2022-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Above', max_length=255),
        ),
    ]
