# Generated by Django 3.2.16 on 2022-11-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit', '0007_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
